
CREATE TABLE T_PESSOA_PY (
    id NUMBER PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    cpf CHAR(11) UNIQUE NOT NULL,
    email VARCHAR2(100),
    telefone VARCHAR2(15),
    endereco VARCHAR2(255)
);

SELECT * FROM T_PESSOA_PY;