CREATE TABLE CARRO_PYTHON (
    PLACA VARCHAR2(10),
    MARCA VARCHAR2(50),
    MODELO VARCHAR2(50),
    PROPRIETARIO VARCHAR2(100),
    ANO INT,
    SALARIO FLOAT,
    DATA_NASCIMENTO DATE,
    ATIVO CHAR(1)
                );

SELECT * FROM CARRO_PYTHON;